Routes and public route component
samir-satpute/React-Assignment pull request #1
Opened 2021-09-29 13:23 UTC by samir-satpute

1) Route and route-guard
2) sign in and signup components
3) Create a store with redux

2021-10-14 13:09 UTC, chetanbura requested changes
Partially reviewed
1. Form HOC
2. Form validation in helper or in hoc
3. Form elements onChange events need to be used as a helper or in HOC
4. Table HOC needs to be implemented
5. Use metadata to optimize wherever mentioned
6. Remove unwanted code from all files
7. Remove unwanted extra lines, try to use prettier to maintain need code

2021-10-14 13:09 UTC, chetanbura commented on src/App.js
> +            // </div>
Remove commented code from all files

2021-10-14 13:09 UTC, chetanbura commented on src/App.js
> +        </Suspense>
Missing Error boundary on route level

2021-10-14 13:09 UTC, chetanbura commented on src/hoc/FormElement.js
> +    )
Implement other form elements as well.
and try to achieve onChange event and validation logic in hoc or in helper

2021-10-14 13:09 UTC, chetanbura commented on src/initialiseFirebase.js
> +    // measurementId: process.env.Firebase_Measurement_Id
use env vars for credential or confidential

2021-10-14 13:09 UTC, chetanbura commented on src/layout/LeftsideMenuBar.js
> +                </Menu.Item>
Optimise this with metadata using map

2021-10-14 13:09 UTC, chetanbura commented on src/layout/NonAuthLayout.js
> +        <Fragment>
Replace `<Fragment>` with `<>` as they both does the same job so optimze

2021-10-14 13:09 UTC, chetanbura commented on src/pages/Book/index.js
> +                            </Form.Group>
Use Form HOC

2021-10-14 13:09 UTC, chetanbura commented on src/pages/BookList/index.js
> +    };
Try to implement this logic via helper class or in HOC

2021-10-14 13:09 UTC, chetanbura commented on src/pages/BookList/index.js
> +        })
Try to use `async` n `awaits` instead `then`

2021-10-14 13:09 UTC, chetanbura commented on src/pages/BookList/index.js
> +        let err = await validateForm();
for making await you need to specify validateForm method should return promise

2021-10-14 13:09 UTC, chetanbura commented on src/pages/BookList/index.js
> +                </Table>
Create reusable TableHoc component where you can send metadata as props for title and table data and use this every where

2021-10-14 13:09 UTC, chetanbura commented on src/pages/BookList/index.js
> +                                    label='Title'
Use Form HOC

2021-10-14 13:09 UTC, chetanbura commented on src/pages/Dashboard/index.js
> +
Forllow coding standard practice and try to use Prettier and remove empty lines from all files

2021-10-14 13:09 UTC, chetanbura commented on src/pages/MyOrder/index.js
> +                </Table.Body>
Use Table HOC as mention above

2021-10-14 13:09 UTC, chetanbura commented on src/pages/Signin/index.js
> +                                onChange: handleChange
try to make Form HOC minimal and pass props what requires and change event and validations need to handle in single place not on every forms

2021-10-14 13:09 UTC, chetanbura commented on src/pages/Signup/index.js
> +                                    label='Customer'
Use FormHOC

2021-10-14 13:09 UTC, chetanbura commented on src/pages/Users/index.js
> +                        <Table.HeaderCell>First Name</Table.HeaderCell>
Use Table HOC

2021-10-14 13:09 UTC, chetanbura commented on src/pages/Users/index.js
> +    </Table.Footer> */}
remove unwanted code from all files

2021-10-14 13:09 UTC, chetanbura commented on src/routes/index.js
> +      },
Ues these meta data for build menu dynamically

2021-10-14 13:09 UTC, chetanbura commented on src/routes/route-guard.js
> +      next.redirect('/');
Instead of this, you can filter in App.js according to with roles access, or you can optimize this logic in better way

2021-10-14 13:09 UTC, chetanbura commented on src/store/action/authAction.js
> +                        //redirect to user not found or 404 error page
404 missing

2021-10-14 13:09 UTC, chetanbura commented on src/util/secureStorage.js
> +    }
explain this workflow, and why it is required

2021-10-25 07:37 UTC, merged

2021-10-25 07:45 UTC, samir-satpute commented on src/hoc/FormElement.js
> +    )
Done

2021-10-25 07:45 UTC, samir-satpute commented on src/layout/NonAuthLayout.js
> +        <Fragment>
done

2021-10-25 07:45 UTC, samir-satpute commented on src/pages/Book/index.js
> +                            </Form.Group>
done

2021-10-25 07:45 UTC, samir-satpute commented on src/pages/BookList/index.js
> +    };
done

2021-10-25 07:46 UTC, samir-satpute commented on src/pages/BookList/index.js
> +        })
done

2021-10-25 07:46 UTC, samir-satpute commented on src/pages/BookList/index.js
> +        let err = await validateForm();
done

2021-10-25 07:46 UTC, samir-satpute commented on src/pages/BookList/index.js
> +                </Table>
done

2021-10-25 07:46 UTC, samir-satpute commented on src/pages/BookList/index.js
> +                                    label='Title'
done

2021-10-25 07:46 UTC, samir-satpute commented on src/pages/Dashboard/index.js
> +
done

2021-10-25 07:47 UTC, samir-satpute commented on src/pages/MyOrder/index.js
> +                </Table.Body>
done

2021-10-25 07:47 UTC, samir-satpute commented on src/pages/Signin/index.js
> +                                onChange: handleChange
done

2021-10-25 07:47 UTC, samir-satpute commented on src/pages/Signup/index.js
> +                                    label='Customer'
Done

2021-10-25 07:47 UTC, samir-satpute commented on src/pages/Users/index.js
> +                        <Table.HeaderCell>First Name</Table.HeaderCell>
done

2021-10-25 07:47 UTC, samir-satpute commented on src/pages/Users/index.js
> +    </Table.Footer> */}
done

2021-10-25 07:48 UTC, samir-satpute commented on src/routes/index.js
> +      },
Done

2021-10-25 07:48 UTC, samir-satpute commented on src/routes/route-guard.js
> +      next.redirect('/');
done

2021-10-25 07:48 UTC, samir-satpute commented on src/store/action/authAction.js
> +                        //redirect to user not found or 404 error page
done

2021-10-25 07:50 UTC, samir-satpute commented on src/util/secureStorage.js
> +    }
Done

2021-10-25 07:50 UTC, samir-satpute commented on src/initialiseFirebase.js
> +    // measurementId: process.env.Firebase_Measurement_Id
Done

2021-10-25 07:53 UTC, samir-satpute commented on src/layout/LeftsideMenuBar.js
> +                </Menu.Item>
Done